FROM python:3.10-alpine

# RUN pip3 install flask psycopg2 configparser


RUN \
 apk add --no-cache postgresql-libs && \
 apk add --no-cache --virtual .build-deps gcc musl-dev postgresql-dev && \
 python3 -m pip install flask psycopg2 configparser --no-cache-dir && \
 apk --purge del .build-deps

WORKDIR {{ docker_app_src_pref }}

COPY . .

ENTRYPOINT [ "python3", "{{ docker_app_src[0] }}" ]
CMD [ "--host=0.0.0.0" ]

EXPOSE 80
