---

- name: Apt "update_cache=yes" if the last one is more than 3600 seconds ago
  ansible.builtin.apt:
    update_cache: yes
    cache_valid_time: 3600
  ignore_errors: yes

- name: Install common packages
  ansible.builtin.package:
    name: "{{ item }}"
    state: present
  with_items: "{{ packages }}"

- name: Install common distr-specific packages
  ansible.builtin.package:
    name: "{{ item }}"
    state: present
  with_items: "{{ lookup('vars', 'packages_' + ansible_distribution) }}"
