---

- name: Install OS packages
  ansible.builtin.package:
    name: "{{ item }}"
    state: present
  with_items: "{{ packages }}"

- name: Install k8s tools
  snap:
    classic: yes
    name:
    - helm
    - kubectl

- name: Install k9s
  unarchive:
    remote_src: yes
    src:  "{{ k9s_url }}"
    dest: /usr/bin/
    mode: '0755'
    owner: root
    group: root

- name: Install Helm plugin
  kubernetes.core.helm_plugin:
    plugin_path: "{{ item }}"
    state: present
  with_items:
  - https://github.com/databus23/helm-diff
  - https://github.com/aslafy-z/helm-git

- name: Install python packages for k8s
  ansible.builtin.pip:
    name:
    - kubernetes >= 12.0.0
    - PyYAML >= 3.11
    - jsonpatch

- name: Install kubectl linstor plugin
  ansible.builtin.unarchive:
    src: https://github.com/piraeusdatastore/kubectl-linstor/releases/download/v0.1.2/kubectl-linstor-v0.1.2-linux-amd64.tar.gz
    dest: /usr/bin
    remote_src: yes
    include:
    - kubectl-linstor
    mode: 0755
    owner: root
    group: root
