---

- name: Set ip4 forwarding
  sysctl:
    name: net.ipv4.ip_forward
    value: '1'
    sysctl_set: yes
    state: present
    reload: yes

#- name: Set arp_ignore=1
#  sysctl:
#    name: net.ipv4.conf.all.arp_ignore
#    value: '1'
#    sysctl_set: yes
#    state: present
#    reload: yes

#- name: Set arp_announce=2
#  sysctl:
#    name: net.ipv4.conf.all.arp_announce
#    value: '2'
#    sysctl_set: yes
#    state: present
#    reload: yes

