apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: loki-ingress-srv
  namespace: serve
spec:
  rules:
  - host: "loki-srv.{{ dns_zone_srv }}"
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: grafana-loki-gateway
            port:
              number: 80
